baseURL = "http://hugo.api/"
languageCode = "en-us"
title = "rougon"

[outputs]
  page = ["json"]
  home = ["json"]
  section = ["json"]
  taxonomy = ["json"]
  taxonomyTerm = [ "json" ]

[taxonomies]
  sport = "sports"

[permalinks]
  page = "/:section/:title/"